### ISSUE TITLE
ecl fails

### ISSUE THREAD

**Issue by jgarte** [byulparan/cl-collider#127]
Hi is it known that cl-collider fail to build on ecl?

**Comment by byulparan** [comment]
today, I tried build cl-collider on ecl.
- macOS 12.6.3
- ECL (Embeddable Common-Lisp) 21.2.1 (git:8cffaf858cb3d63554ca038064111a4f9598e227)

It build well without problem. what's your problem?

but I have other problem about run external-process.

```lisp
> (uiop:run-program "ls")

Condition of type: SIMPLE-ERROR
si_system not implemented
C library explanation: No such file or directory.
```

so can't bootup `scsynth`, because It use `uiop:run-program`.
It seems problem `uiop` or `ecl`, It needs more test.

**Comment by byulparan** [comment]
I tested on ecl 23.9.9 and run well without problem.
I closed this issue.
