### ISSUE TITLE
Ignore UGens on boot

### ISSUE THREAD

**Issue by kflak** [byulparan/cl-collider#142]
Hi,

Is there a way to specify some directories that gets ignored when booting the server? I have a whoooole bunch of UGens from a quark that seem to have no cl-collider equivalent, and I get outputs like this when booting:

```
while reading file: '/home/kf/.local/share/SuperCollider/synthdefs/komet_synth_musliplayer1_granular_gate_ladder_2.scsyndef'exception in GraphDef_Load: UGen 'KometDelay' not installed.
while reading file: '/home/kf/.local/share/SuperCollider/synthdefs/komet_fx_kometdelay_channelized_2.scsyndef'exception in GraphDef_Load: UGen 'GuitarStreng' not installed.
while reading file: '/home/kf/.local/share/SuperCollider/synthdefs/komet_synth_guitarstreng_physical_adsr_korg35_2.scsyndef'exception in GraphDef_Load: UGen 'NylonStreng' not installed.
while reading file: '/home/kf/.local/share/SuperCollider/synthdefs/komet_synth_nylonstreng_physical_adsr_korg35_2.scsyndef'exception in GraphDef_Load: UGen 'Klimit' not installed.
.....
etc etc
```
This takes quite a while to chew through, so I'd rather be able to tell cl-collider not to try installig them. Or maybe I'm thinking about it the wrong way?

**Comment by defaultxr** [comment]
I think the cause of these errors isn't that cl-collider doesn't support these UGens, but rather that the SuperCollider server is attempting to load SynthDefs that contain UGens that the server is not aware of. cl-collider will not generate errors for UGens that it doesn't know; you just won't be able to use them.

The problem is probably that you have UGens installed in a location outside of the default list of paths that cl-collider tells SuperCollider to look for UGens. So you could probably avoid these errors by doing the following before you tell cl-collider to boot the server:

```lisp
(push "/path/to/where/those/ugens/are/installed/" cl-collider:*sc-plugin-paths*)
```

Just change the path to where the binaries of those external UGens get installed. For example, for me on Arch Linux, this is `/usr/share/SuperCollider/Extensions/` .

**Comment by kflak** [comment]
Great, that works! `/usr/share/SuperCollider/Extensions/` is already in that list, but `~/.local/share/SuperCollider/Extensions/` wasn't (also on Arch Linux).

**Comment by kflak** [comment]
Follow-up question: does this mean that cl-collider is able to use synthdefs with unsupported UGens if they exist on the server, fx. if I load them on the sclang side?

**Comment by defaultxr** [comment]
> Follow-up question: does this mean that cl-collider is able to use synthdefs with unsupported UGens if they exist on the server, fx. if I load them on the sclang side?

Oh, sorry, I was wrong about that; just using `cl-collider:synth` won't allow you to trigger synthdefs stored by sclang. scsynth's `/d_load` OSC command does allow a synthdef to be loaded from a file, but it looks like cl-collider doesn't do that for pre-existing synthdefs yet. Perhaps it will in the future though...

**Comment by defaultxr** [comment]
But it looks like you can load them manually by sending a OSC message to the server:

```lisp
(cl-collider::send-message *s* "/d_loadDir" "/path/to/your/synthdefs/")
```

This will load all of the synthdefs in the specified directory, and then they can be played with `cl-collider:synth`.

**Comment by kflak** [comment]
Cool! Thanks for the explanation.
