### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by TatriX** [byulparan/cl-collider#2]
I'm trying to follow your tutorial (https://www.youtube.com/watch?v=JivNMDUqNQc):

``` lisp
(ql:quickload :sc)
(in-package :sc)
(setf *sc-synth-program* "/usr/bin/scsynth")
(push "/usr/lib/SuperCollider/plugins/" *sc-plugin-paths*)
(push "/usr/share/SuperCollider/Extensions/" *sc-plugin-paths*)
(setf *s* (make-external-server "localhost" :port 4444))
(server-boot *s*) ; returns nil
(play (sin-osc.ar [440 441] 0 .2)) ; nothing happens
```

cl-collider from git, arch-linux, sbcl 1.3.1, supercollider version:  3.6.6-2
`scide` makes sounds without problems.

Any ideas?

**Comment by byulparan** [comment]
hmm...  when  you input `(server-boot *s*)` ... what print in slime repl buffer?
do scsynth server bootup to normally?
how about run `(server-query-all-nodes)`?

**Comment by TatriX** [comment]
``` (server-boot *s*)```
prints in the ```*inferior-lisp*``` buffer:
```
JACK compiled with System V SHM support.
loading driver ..
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 1024
SuperCollider 3 server ready.
Zeroconf: failed to create client: Daemon not running
```

``` common
sc> (server-query-all-nodes) 
NODE TREE Group 0
   1 group
      1000 temp-synth
```

**Comment by TatriX** [comment]
No ideas?

**Comment by byulparan** [comment]
maybe...It seems Jack server problem.
because scsynth is bootup and communication with cl-collider looks ok.

` connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)`

so... It need some script for jack server...
1. jack server bootup 
2. scsynth bootup 
3. connect scsynth IO with jack server.

then ` (setf *sc-synth-program* "/usr/bin/that-some-script")`

sorry, currently I don't have linux machine but as soon as I will update that script.

**Comment by TatriX** [comment]
Not sure if it can help but I've tried to run sclang and it works:
```
init_OSC
empty
compiling class library...
	NumPrimitives = 679
	compiling dir: '/usr/share/SuperCollider/SCClassLibrary'
	compiling dir: '/usr/share/SuperCollider/Extensions'
	pass 1 done
	numentries = 781741 / 10829266 = 0.072
	4963 method selectors, 2182 classes
	method table size 11679416 bytes, big table size 86634128
	Number of Symbols 11468
	Byte Code Size 357892
	compiled 319 files in 0.26 seconds
compile done
Help tree read from cache in 0.0016241073608398 seconds
LID: event loop started
Class tree inited in 0.01 seconds
Welcome to SuperCollider 3.6.6. For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
sc3> s.boot
booting 57110
localhost
sc3> Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
no message buffer overruns
no message buffer overruns
no message buffer overruns
jackdmp 1.9.10
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2014 Grame.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
audio_reservation_init
Acquire audio card Audio0
creating alsa driver ... hw:0|hw:0|1024|2|48000|0|0|nomon|swmeter|-|32bit
configuring for 48000Hz, period = 1024 frames (21.3 ms), buffer = 2 periods
ALSA: final selected sample format for capture: 32bit integer little-endian
ALSA: use 2 periods for capture
ALSA: final selected sample format for playback: 32bit integer little-endian
ALSA: use 2 periods for playback
JackDriver: client name is 'SuperCollider'
SC_AudioDriver: sample rate = 48000.000000, driver's block size = 1024
JackDriver: connected  system:capture_1 to SuperCollider:in_1
JackDriver: connected  system:capture_2 to SuperCollider:in_2
JackDriver: connected  SuperCollider:out_1 to system:playback_1
JackDriver: connected  SuperCollider:out_2 to system:playback_2
SuperCollider 3 server ready.
JackDriver: max output latency 42.7 ms
Receiving notification messages from server localhost
Shared memory server interface initialized
```

**Comment by byulparan** [comment]
when you run sc synth server in cl-collider, then run QjackCtl program(It manage to jack server in GUI)
If you can see SuperCollider in connect view of QjackCtl, then connect SuperCollider Out_1,Out_2 to system playback_1, playback_2  manually.
I run ubuntu on virtual box, then I can hear sound. ...plz test it.

**Comment by TatriX** [comment]
Worked like a charm!

**Comment by byulparan** [comment]
I will find which way of connection automatically. 
until then, please connect it manually. Thank you!

**Comment by liuxueyang** [comment]
on my OS X, sbcl, `(server-boot *s*)` doesn't print anything, it just return nil.

**Comment by defaultxr** [comment]
I think it should probably be up to the user to set up JACK to automatically connect the SuperCollider server how they want it. For example, Qjackctl has the "Patchbay" feature which lets you graphically set up connections for JACK clients which will be made automatically whenever those programs are started.

However, if we want to manually connect SuperCollider to the system output, these two commands are working for me:

`jack_connect SuperCollider:out_1 system:playback_1`
`jack_connect SuperCollider:out_2 system:playback_2`

`jack_connect` is a standard utility that is installed with both `jack` and `jack2`, at least for me on Arch Linux.

@liuxueyang `server-boot` should not return nil, it should always return the rt-server object. However if you weren't seeing the scsynth output that TatriX posted then that is likely because you are using SBCL, and cl-collider was not set up to send scsynth's output to the REPL. However as of commit 8fac335e27cd60bcdacce5c8839ea7a33e2601a6 , this problem should be fixed and you should see the scsynth output in your REPL or *inferior-lisp* buffer. Let me know if you're still having the same problem when using the latest version of cl-collider.
