### ISSUE TITLE
Error when quickloading the library

### ISSUE THREAD

**Issue by ntrocado** [byulparan/cl-collider#27]
I get the following error. I'm on Win10/Slime/SBCL. What's going on?

```
CL-USER> (ql:quickload :sc)
To load "sc":
  Load 1 ASDF system:
    sc
; Loading "sc"
; 
; caught ERROR:
;   (during macroexpansion of (SETF *SC-PLUGIN-PATHS*))
;   error while parsing arguments to DESTRUCTURING-BIND:
;     too few elements in
;       (*SC-PLUGIN-PATHS*)
;     to satisfy lambda list
;       (SB-IMPL::PLACE SB-IMPL::VALUE-FORM . SB-IMPL::MORE):
;     at least 2 expected, but got 1
....; 
    ; compilation unit aborted
    ;   caught 2 fatal ERROR conditions
    ;   caught 1 ERROR condition
; Evaluation aborted on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {100BE26223}>.

```

**Comment by defaultxr** [comment]
It's probably because of the variable definitions in server.lisp, i.e. the ones starting on [line 6](https://github.com/byulparan/cl-collider/blob/6a0da5cd61dc60c191f36656c5674d7a80ed1471/server.lisp#L6). There are values for Mac/Darwin and Linux, but none for Windows. You'd need to edit those three variables to include directives for Windows that point to the equivalent paths on that OS. Once you've done that then it should work properly... Or at least will cause a different error to occur.

If you do get it working properly, submitting a PR with the changes would be great so future Windows users of the library won't run into the same problem.

**Comment by ntrocado** [comment]
I set the correct paths for Windows. Now it loads but I can't start the server, because it produces an error when trying to find /bin/sh. I tried editing the run-program function to make it execute the program directly. I now get a sockets error, and if I retry starting the server I get a scheduler error. Unfortunately I don't have the skills to debug this by myself...

**Comment by defaultxr** [comment]
Can you copy/paste the error messages for those errors?

**Comment by ntrocado** [comment]
Socket error in "recvfrom": 10054 (Uma ligação existente foi forçada a fechar pelo anfitrião remoto.)
   [Condition of type SB-BSD-SOCKETS:SOCKET-ERROR]

Restarts:
 0: [ABORT] abort thread (#<THREAD "OSC device receive thread" RUNNING {101153B353}>)

**Comment by ntrocado** [comment]
If I start the server manually (by running scsynth from the terminal), and then try to call server-boot I get:

Unknown CFFI type SCHEDULER::SCHED-POLICY
   [Condition of type CFFI::UNDEFINED-FOREIGN-TYPE-ERROR]

Restarts:
 0: [ABORT] abort thread (#<THREAD "localhost scheduler thread" RUNNING {101061E273}>)

But then I abort the thread and the library actually works!

**Comment by byulparan** [comment]
sorry for very late reply...  
cl-collider support Win10/Slime/SBCL+CCL now. 
`Socket error in "recvfrom": 10054` problem is very difficult to solve.
I need more test. 

[cl-collider on Windows10](https://youtu.be/pCEfV4jOdUA)

**Comment by ntrocado** [comment]
This is great, thank you!
I can confirm everything is working on Win10/Sly/SBCL.
I have to set the paths directly in server.lisp, otherwise I get a pathname error when quickloading.
The socket error is gone...
