### ISSUE TITLE
Mix.fill alternative

### ISSUE THREAD

**Issue by TatriX** [byulparan/cl-collider#3]
I'm reading supper collider [tutorial](http://doc.sccode.org/Tutorials/Getting-Started/07-Mix-it-Up.html) and reproducing it in cl-collider.
There is an example:
```
(
    var n = 8;
    { Mix.fill(n, { SinOsc.ar(500 + 500.0.rand, 0, 1 / n) }) }.play;
)
```
I didn't find the mix.fill method and just used ```loop``` like this:
```lisp
(let ((n 8)) 
	   (play (loop repeat n
		    collect (sin-osc.ar (+ 500 (random 500)) 0 (/ 1 n)))))
```
Is this is an idiomatic solution or I'm missing something?

**Comment by byulparan** [comment]
correctly,
````cl
    (let ((n 8)) 
        (play (mix (loop repeat n
             collect (sin-osc.ar (+ 500 (random 500)) 0 (/ 1 n))))))
````

I'm just don't implementaton it. because I think that syntax sugar.
I also use 'loop' instead 'Mix.fill'.
Each people needs each utility function(but It seems useful for less code and general usage).
so You can make your own expansion cl-collider or I will add it next release :-)
Thank you for suggestion.

**Comment by TatriX** [comment]
Got it, thank you. Where can I ask other questions about cl-collider not pollution github issues?
