### ISSUE TITLE
(server-status *s*) returns `; No value`

### ISSUE THREAD

**Issue by liuxueyang** [byulparan/cl-collider#4]
I test it on MacBook Air. 
when I use `(server-status *s*)` or `(server-query-all-nodes *s*)` to list running id. They all returns `; No value`. I have to run `(server-quit *s*)` to stop it and then boot server.
I watch your tutorial on YouTube, you can display running ids on it. Why id does not work on my computer. Thank you. :)

**Comment by byulparan** [comment]
When you run `(play (sin-osc.ar 440 0 0.2))` ,can you hear sound?
if so that's normal. maybe display message to \*inferior-lisp\* buffer instead \*slime-repl\* buffer.
default, slime display message to \*inferior-lisp\* buffer if you run print function in secondrary thread.
https://www.common-lisp.net/project/slime/doc/html/Global-IO-Redirection.html
or add this line to your .emacs file.
    
    (add-hook 'slime-connected-hook
        (lambda ()
          (when (find-if #'(lambda (buffer) (string= "*inferior-lisp*" (buffer-name buffer))) (buffer-list))    
              (slime-redirect-inferior-output))))

If don't fix it, report it again! Thank you~ :-)

**Comment by liuxueyang** [comment]
Yes, I can hear sound when I run `(play (sin-osc.ar 440 0 0.2))`. 
I add that slime configuration to my init.el and restart sbcl. It works! Thank you very much! :) 👍 👍 👍
