### ISSUE TITLE
No sound with default make-external-server on linux due to -H cl-collider option

### ISSUE THREAD

**Issue by VaclavSynacek** [byulparan/cl-collider#71]
I have no sound on linux after `make-external-server` and `server-boot` with default values. This is because of option `-H cl-collider` passed to `scsynth`. If I comment out this option everything works as expected.

The `-H` option and the default value of `cl-collider` was introduced in #62 by @vrx . I have no idea what this is needed for and especially I do not understand why one would want this default value. SuperCollider's documentation suggests a sane default is not to set this and use system default input and output devices instead.

Could we agree on either reverting #62 or changing the default to nil?

**Comment by defaultxr** [comment]
I think setting -H to `cl-collider` is to differentiate it from scsynth when run from sclang/SC itself. Otherwise if you run scsynth from cl-collider and from SC at the same time, I believe JACK will rename the second one to something like `SuperCollider<2>`. To me it seems better to have the consistency of each JACK client always having the same name. But I guess running both at the same time is not a common case (I only do it these days when I want to compare the behavior of cl-collider to regular SuperCollider), and most people would probably find it confusing to try out cl-collider and get no sound because their JACK patchbay doesn't see it as the same client.

Maybe a compromise would be if there were some way for cl-collider to ensure it was connected to JACK's outputs? I can't remember if this is the case currently.

Either way, though, I would be fine with reverting the `-H` part of #62 if others agree.

**Comment by VaclavSynacek** [comment]
As an alternative to reverting see #74. It is still a breaking change for people expecting the device to be "cl-collider" but should now work mostly out of the box for everybody else.
